version: '3'

services:
  postgres:
    image: "postgres:16.4"
    container_name: postgres
    ports:
      - "5430:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=usr
      - POSTGRES_DB=testdb
    network_mode: bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M