version: '3'

services:
  postgres:
    image: "postgres:16.4"
    container_name: postgres
    ports:
      - "5430:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=usr
      - POSTGRES_DB=testdb
    network_mode: bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
  links-service:
    build: .
    container_name: links-service
    ports:
      - 8081:8080
    env_file:
      - .env
    environment:
      - DSN=host=host.docker.internal user=usr password=pwd dbname=testdb port=5430 sslmode=disable
    entrypoint: ["bash", "-c", "./migrate && ./app"]
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
